POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Category 2",
    "description": "Category 2 description"
}

###
GET http://localhost:8080/category/fb4a9b0b-87ce-4edb-8210-98a8f3ff2305 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###
GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###
POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "image_url": "http://www.google.com",
    "category_id": "fb4a9b0b-87ce-4edb-8210-98a8f3ff2305"
}

###
GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###
GET http://localhost:8080/product/f57cf191-0ec8-4b8f-99a2-ab18a5ab9bce HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###
GET http://localhost:8080/product/category/fb4a9b0b-87ce-4edb-8210-98a8f3ff2305 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 2",
    "description": "Product 2 description",
    "price": 200,
    "image_url": "http://www.google.com",
    "category_id": "fb4a9b0b-87ce-4edb-8210-98a8f3ff2305"
}